site_name: Dummy Docs
site_description: "One searchable home for code-level docs, R&D notes and data inventories."
site_url: ""                # add a real URL after you deploy
repo_url: https://github.com/dummu/dummy
edit_uri: edit/main/
docs_dir: docs  # Source documentation
site_dir: build/site  # Output directory for the built site

# ---------- Theme ----------
theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/favicon.png
  palette:
    # ---------- Dark Mode ----------
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: light green

    # ---------- Light Mode ----------
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: green
      accent: light green

# ---------- Navigation ----------
nav:
    - Overview: 'index.md'
    - Analysis: 'analysis.md'
    - Detail design: 'detail-design.md'
    - Installation: 'installation.md'
    - Usage Guide: 'usage.md'

